trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  WEBSITE_REPO: "https://github.com/Ginika1990/t2uhub-website.git"

steps:
- checkout: self

- task: TerraformInstaller@1
  inputs:
    terraformVersion: '1.6.0'

- script: terraform init
  displayName: 'Terraform Init'

- script: terraform apply -auto-approve
  displayName: 'Terraform Apply'

- script: |
    echo "##vso[task.setvariable variable=VM_IP]$(terraform output -raw public_ip_address)"
  displayName: 'Get VM IP'

- task: DownloadSecureFile@1
  name: downloadKey
  inputs:
    secureFile: 't2u-key'

-- task: DownloadSecureFile@1
  name: downloadKey
  inputs:
    secureFile: 't2u-key'

- task: SSH@0
  inputs:
    sshEndpoint: ''
    runOptions: 'inline'
    sshPublicKey: false
    sshKey: '$(Agent.TempDirectory)/$(downloadKey.secureFilePath)'
    userName: 'azureuser'
    hostname: $(VM_IP)
    port: '22'
    inline: |
      sudo apt update
      sudo apt install nginx git -y
      sudo rm -rf /var/www/html/*
      sudo git clone $(WEBSITE_REPO) /var/www/html
      sudo systemctl restart nginx
  displayName: 'Deploy Website Code'
 

